language: cpp
if: tag IS blank
matrix:
    include:
        - os: osx
          osx_image: xcode9.2
          compiler: clang

install:
    - cd ..
    - git clone https://github.com/chibidev/git-dependencies.git
    - export PATH=$PATH:`pwd`/git-dependencies
    - cd emgen
    - brew install python3 llvm
    - export LLVM_CONFIG=`find /usr/local/Cellar -name llvm-config`

script:
    - git-dependencies update -r
    - mkdir build && cd build
    - cmake -D LLVM_VERSION_EXPLICIT=`clang -v 2>&1 | grep version | cut -d ' ' -f 4` -D LIBCLANG_INCLUDE_DIR=`$LLVM_CONFIG --includedir` -D LIBCLANG_LIBRARY=/Applications/Xcode.app/Contents/Frameworks/libclang.dylib -D CLANG_BINARY=/usr/bin/clang -D LIBCLANG_SYSTEM_INCLUDE_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -D CMAKE_BUILD_TYPE=Release ..
    - cmake --build . --target emgen

before_deploy:
    - cd $TRAVIS_BUILD_DIR
    - export RELEASE_TAG=v`cat src/main.cpp | grep version | grep static | cut -d '"' -f 2`

deploy:
    provider: releases
    api_key:
        secure: biPSBrhjo3KES7BU9HcHm0sXc74nCoqhKR7eixNIrXdKaRr6GJHZxBd405KHVIgNKoAFbtOOsZpfU+vpnMdGa2wZIlaRdwioYdl9yUMITlWaOsdsMxmc/xV9iQaNlCIiOekxni7L6CXlKGgF6Hbg5rNPZviqhbDHxG1smCLYaXVR2mKJkYq/Scj17adn8h5GoLJQ+Vog0lrqvrUWUFt5fKwXan8iep4RoakIWnuxSZOmD1wfOCNN7v/4BsL4n6sk2rkOPtaULibzAirwOQL0kVJLFpnMiAyuHqs5f987JEHWyuEVR+H19g+3ZRuKa+fSMcsJA0wy50vesYrfQKTbHfEBnHVMXilbWxI6/g+hw6sMx0shUKpSIfbG2cqM/ussIeu/FlbTYz1P558bXPrucpehBRw2FSX1yLmS1T0dWxbI5IqVb7EBQxrQ5MpO0jKh5PNSQoev8NWjg1hxR7HweJ51YCAb74oOhSzmoNq1tlTA89aMzr3vph/fvXjiYx3xu5m4NEjPt0ihNTBrtNe1HW+yvUI2WiegCGGmxLCFAcPM9uuV6Agom5B6M13rzm81TClZUYH0TUGxZFWog4YOxv+vpxPyWjhxIkaAAYmUv77UNQxaQduCWhOlemZgsBGIKuBA+FwToROmp0RzzyMCNOO3E+qCsFXMHWlVxMQ8C+Q=
    file: $TRAVIS_BUILD_DIR/build/emgen
    skip_cleanup: true
    draft: false
    tag_name: $RELEASE_TAG
    name: emgen macOS $RELEASE_TAG
    on:
        repo: chibidev/emgen
        branch: master

